name: pyvespa documentation search feed
on:
  push:
    branches: [master]

env:
  DATA_PLANE_PUBLIC_KEY: ${{ secrets.VESPA_TEAM_DATA_PLANE_PUBLIC_CERT }}
  DATA_PLANE_PRIVATE_KEY: ${{ secrets.VESPA_TEAM_DATA_PLANE_PRIVATE_KEY }}
  VESPA_CLI_DATA_PLANE_CERT: ${{ secrets.VESPA_TEAM_VESPA_CLI_DATA_PLANE_CERT }}
  VESPA_CLI_DATA_PLANE_KEY: ${{ secrets.VESPA_TEAM_VESPA_CLI_DATA_PLANE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.9"

      - name: Install Sphinx
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -e .[docs,feed]

      - name: Build site
        run: |
          mkdocs build --site-dir docs/sphinx/build

          # Add front matter and strip liquid macros from html files
          find docs/sphinx/build -name \*.html | \
            while read f; do \
              { echo "---"; echo "---"; sed 's/{%/{ %/g; s/%}/% }/g; s/{{/{ {/g; s/}}/} }/g' < ${f}; } >${f}.new; \
              mv ${f}.new ${f}; \
            done

          bundle exec jekyll build -s docs/sphinx/build/ -p _plugins-vespafeed --config _config.yml

      - name: Feed site
        run: |
          # The python scripts below uses the Vespa CLI for feeding / data access.
          # See https://docs.vespa.ai/en/vespa-cli.html.
          # The environment variables below have credentials for endpoint access -
          # use the key/cert files in .vespa and paste their content into GitHub Secrets.
          export VESPA_CLI_DATA_PLANE_CERT
          export VESPA_CLI_DATA_PLANE_KEY
          ./feed_to_vespa.py _config.yml

      - name: Convert all notebooks to md
        run: |
          jupyter nbconvert --to markdown docs/sphinx/source/examples/*.ipynb --output-dir='./markdown_notebooks/'
          jupyter nbconvert --to markdown docs/sphinx/source/*.ipynb --output-dir='./markdown_nooteboks/'

      - name: Feed paragraphs site
        run: |
          ./feed-split.py pyvespa_index.json https://vespa-engine.github.io/pyvespa/ questions.jsonl
          ./feed_to_vespa.py _paragraphs_config.yml

      - name: Feed suggestions
        run: |
          ./feed_to_vespa.py _suggestions_config.yml
