name: MKDocs test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - mastee
jobs:
  mk-docs-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.3/pandoc-3.3-1-amd64.deb
          sudo dpkg -i pandoc-3.3-1-amd64.deb
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml

      - name: Install dependencies
        run: |
          pip install -e .[docs]
      - name: Run tests
        run: |
          pytest tests/mktestdocs -s -v
  mk-docs-deploy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -e .[docs]

      - name: Test build
        run: mkdocs build
